### PR TITLE
Conversion to Paket

### PR DESCRIPTION
**Pull request by forki**
Are you interested in this?

### CODE REVIEW

**Comment by dmitry-a-morozov** [comment]
@forki Please, give me some time to think it through.
I have 3 concerns:
1) Paket is yet to reach maturity level
2) I understand problem Paket tries to solve but I don't have those for this library because dependencies are trivial.
3) I don't have any Paket experience so there will be some learning curve. I don't think it will be hard but I have gazillion other things to do.  

That said I admire and support your effort so I'm willing to take this relatively small risk. Give me couple days to decide. 

P.S. Have RProvider and Deedle been converted to Paket?

**Comment by forki** [comment]
Yes I totally understand.

Deedle pull request is still open
https://github.com/BlueMountainCapital/Deedle/pull/288

**Comment by christolo** [comment]
Any update on this? Paket would be nice to have.

**Comment by dmitry-a-morozov** [comment]
@christolo Can you review this PR making sure it can be merged?
Once it's done I will merge.

**Comment by christolo** [comment]
Sure. Not sure of the best way to handle this though. Try to merge across forks? Or just fork and replay @forki changes?

**Comment by dmitry-a-morozov** [comment]
I'm not sure either. 
Probably fork and reply will work.

**Comment by forki** [comment]
I can try to cleanup this.

**Comment by forki** [comment]
I updated the PR, but it#s not building. Any ideas?

**Comment by sergey-tihon** [comment]
Could you try build it using `AppVeyor`?
I think that it is `Mono` specific issue. Probably `PresentationFramework.dll` differ from `Windows` one.

**Comment by forki** [comment]
https://ci.appveyor.com/project/SteffenForkmann/fsharp-desktop-ui

**Pull request merged**
